In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./true_labels_vs_prediction_deepseek_standardEval_without_deepthink.csv")

In [6]:
Mega = pd.read_csv("../../../Dataset Samples/MegaVuln_standard_evaluation.csv")

In [7]:
Mega.columns

Index(['CWE', 'Function', 'is_vul'], dtype='object')

In [12]:
Mega.head()

       CWE                                           Function  is_vul
0     Safe  static void AddQueryTimeStatsToOutput ( SqlRow...   False
1     Safe  static int igb_ndo_set_vf_bw(struct net_device...   False
2  CWE-787  static GF_XMTParser *xmt_new_parser(GF_SceneLo...    True
3     Safe  static int bpf_object__read_kallsyms_file(stru...   False
4  CWE-416  void jsi_UserObjFree(Jsi_Interp *interp, Jsi_U...    True

In [4]:
df.head()

  predictions true_labels  is_vul
0     CWE-787        Safe   False
1     CWE-129        Safe   False
2     CWE-119     CWE-787    True
3     CWE-676        Safe   False
4     CWE-416     CWE-416    True

In [5]:
df.shape

(35387, 3)

In [6]:
df['is_vul'].value_counts()

is_vul
False    28372
True      7015
Name: count, dtype: int64

In [7]:
from AIeval import ModelEval, PlotModelResults

In [9]:
ModelEval(df=df,modelType='generation',filePath='./deepseek_standardEval_binary.txt',targetMethod='binary')

Model type : generation
Method type : binary
The input DataFrame:
  predictions true_labels  is_vul
0     CWE-787        Safe   False
1     CWE-129        Safe   False
2     CWE-119     CWE-787    True
3     CWE-676        Safe   False
4     CWE-416     CWE-416    True
Saving results to ./deepseek_standardEval_binary.txt

--- Evaluation Results ---
Model Type: generation
Method Type: binary
True Positives: 6784
True Negatives: 2788
False Positives: 25584
False Negatives: 231
Total Population for Metrics: 35387
Precision: 20.96%
Recall: 96.71%
F1 Score: 0.3445
Accuracy: 27.05%

Results also saved to ./deepseek_standardEval_binary.txt

In [10]:
ModelEval(df=df,modelType='generation',filePath='./deepseek_standardEval_multiclass.txt',targetMethod='multiclass')

Model type : generation
Method type : multiclass
The input DataFrame:
  predictions true_labels  is_vul
0     CWE-787        Safe   False
1     CWE-129        Safe   False
2     CWE-119     CWE-787    True
3     CWE-676        Safe   False
4     CWE-416     CWE-416    True
Saving results to ./deepseek_standardEval_multiclass.txt

--- Evaluation Results ---
Model Type: generation
Method Type: multiclass
True Positives: 3483
True Negatives: 9239340
False Positives: 32054
False Negatives: 31904
Total Population for Metrics: 9306781
Precision: 9.80%
Recall: 9.84%
F1 Score: 0.0982
Accuracy: 99.31%

Results also saved to ./deepseek_standardEval_multiclass.txt

In [11]:
PlotModelResults(modelName='DeepseekV3.2_Chat_Binary',datasetName='MegaVuln_standard_evaluation',resultsPath='./deepseek_standardEval_binary.txt',outputPath='./')

Results plot saved to: .//DeepseekV3.2_Chat_Binary_results_MegaVuln_standard_evaluation.png

In [12]:
PlotModelResults(modelName='DeepseekV3.2_Chat_Multiclass',datasetName='MegaVuln_standard_evaluation',resultsPath='./deepseek_standardEval_multiclass.txt',outputPath='./')

Results plot saved to: .//DeepseekV3.2_Chat_Multiclass_results_MegaVuln_standard_evaluation.png